export const COMPANIES = [
    { name: 'Google', category: 'FAANG', website: 'https://careers.google.com', applyUrl: 'https://careers.google.com' },
    { name: 'Amazon', category: 'FAANG', website: 'https://amazon.jobs', applyUrl: 'https://amazon.jobs' },
    { name: 'Microsoft', category: 'FAANG', website: 'https://careers.microsoft.com', applyUrl: 'https://careers.microsoft.com' },
    { name: 'Meta', category: 'FAANG', website: 'https://careers.meta.com', applyUrl: 'https://careers.meta.com' },
    { name: 'Apple', category: 'FAANG', website: 'https://jobs.apple.com', applyUrl: 'https://jobs.apple.com' },
    { name: 'Netflix', category: 'FAANG', website: 'https://jobs.netflix.com', applyUrl: 'https://jobs.netflix.com' },
    { name: 'Flipkart', category: 'Product', website: 'https://www.flipkartcareers.com', applyUrl: 'https://www.flipkartcareers.com' },
    { name: 'Paytm', category: 'Product', website: 'https://paytm.com/careers', applyUrl: 'https://paytm.com/careers' },
    { name: 'Swiggy', category: 'Product', website: 'https://careers.swiggy.com', applyUrl: 'https://careers.swiggy.com' },
    { name: 'Zomato', category: 'Product', website: 'https://www.zomato.com/careers', applyUrl: 'https://www.zomato.com/careers' },
    { name: "BYJU'S", category: 'Product', website: 'https://byjus.com/careers', applyUrl: 'https://byjus.com/careers' },
    { name: 'Ola', category: 'Product', website: 'https://ola.careers', applyUrl: 'https://ola.careers' },
    { name: 'Uber', category: 'Product', website: 'https://www.uber.com/us/en/careers', applyUrl: 'https://www.uber.com/us/en/careers' },
    { name: 'PhonePe', category: 'Product', website: 'https://careers.phonepe.com', applyUrl: 'https://careers.phonepe.com' },
    { name: 'CRED', category: 'Startup', website: 'https://careers.cred.club', applyUrl: 'https://careers.cred.club' },
    { name: 'Razorpay', category: 'Startup', website: 'https://razorpay.com/jobs', applyUrl: 'https://razorpay.com/jobs' },
    { name: 'Freshworks', category: 'Product', website: 'https://careers.freshworks.com', applyUrl: 'https://careers.freshworks.com' },
    { name: 'Zoho', category: 'Product', website: 'https://careers.zohocorp.com', applyUrl: 'https://careers.zohocorp.com' },
    { name: 'Infosys', category: 'Service', website: 'https://www.infosys.com/careers', applyUrl: 'https://www.infosys.com/careers' },
    { name: 'TCS', category: 'Service', website: 'https://www.tcs.com/careers', applyUrl: 'https://www.tcs.com/careers' },
    { name: 'Wipro', category: 'Service', website: 'https://careers.wipro.com', applyUrl: 'https://careers.wipro.com' },
    { name: 'Accenture', category: 'Service', website: 'https://www.accenture.com/in-en/careers', applyUrl: 'https://www.accenture.com/in-en/careers' },
    { name: 'Cognizant', category: 'Service', website: 'https://careers.cognizant.com', applyUrl: 'https://careers.cognizant.com' },
    { name: 'Capgemini', category: 'Service', website: 'https://www.capgemini.com/in-en/careers', applyUrl: 'https://www.capgemini.com/in-en/careers' },
    { name: 'HCL Technologies', category: 'Service', website: 'https://www.hcltech.com/careers', applyUrl: 'https://www.hcltech.com/careers' },
    { name: 'Tech Mahindra', category: 'Service', website: 'https://careers.techmahindra.com', applyUrl: 'https://careers.techmahindra.com' },
    { name: 'Mphasis', category: 'Service', website: 'https://careers.mphasis.com', applyUrl: 'https://careers.mphasis.com' },
    { name: 'Hexaware', category: 'Service', website: 'https://hexaware.com/careers', applyUrl: 'https://hexaware.com/careers' },
    { name: 'LTIMindtree', category: 'Service', website: 'https://www.ltimindtree.com/careers', applyUrl: 'https://www.ltimindtree.com/careers' },
    { name: 'IBM', category: 'Service', website: 'https://careers.ibm.com', applyUrl: 'https://careers.ibm.com' },
    { name: 'Deloitte', category: 'Consulting', website: 'https://www2.deloitte.com/careers', applyUrl: 'https://www2.deloitte.com/careers' },
    { name: 'PwC', category: 'Consulting', website: 'https://www.pwc.in/careers', applyUrl: 'https://www.pwc.in/careers' },
    { name: 'EY', category: 'Consulting', website: 'https://www.ey.com/en_in/careers', applyUrl: 'https://www.ey.com/en_in/careers' },
    { name: 'KPMG', category: 'Consulting', website: 'https://home.kpmg/in/en/careers', applyUrl: 'https://home.kpmg/in/en/careers' },
    { name: 'McKinsey & Company', category: 'Consulting', website: 'https://www.mckinsey.com/careers', applyUrl: 'https://www.mckinsey.com/careers' },
    { name: 'Boston Consulting Group', category: 'Consulting', website: 'https://careers.bcg.com', applyUrl: 'https://careers.bcg.com' },
    { name: 'Bain & Company', category: 'Consulting', website: 'https://www.bain.com/careers', applyUrl: 'https://www.bain.com/careers' },
    { name: 'JP Morgan Chase', category: 'Finance', website: 'https://careers.jpmorgan.com', applyUrl: 'https://careers.jpmorgan.com' },
    { name: 'Goldman Sachs', category: 'Finance', website: 'https://www.goldmansachs.com/careers', applyUrl: 'https://www.goldmansachs.com/careers' },
    { name: 'Morgan Stanley', category: 'Finance', website: 'https://www.morganstanley.com/careers', applyUrl: 'https://www.morganstanley.com/careers' },
    { name: 'Citibank', category: 'Finance', website: 'https://jobs.citi.com', applyUrl: 'https://jobs.citi.com' },
    { name: 'Deutsche Bank', category: 'Finance', website: 'https://careers.db.com', applyUrl: 'https://careers.db.com' },
    { name: 'American Express', category: 'Finance', website: 'https://jobs.americanexpress.com', applyUrl: 'https://jobs.americanexpress.com' },
    { name: 'Barclays', category: 'Finance', website: 'https://home.barclays/careers', applyUrl: 'https://home.barclays/careers' },
    { name: 'HDFC Bank', category: 'Finance', website: 'https://hdfcbank.com/careers', applyUrl: 'https://hdfcbank.com/careers' },
    { name: 'ICICI Bank', category: 'Finance', website: 'https://www.icicicareers.com', applyUrl: 'https://www.icicicareers.com' },
    { name: 'Axis Bank', category: 'Finance', website: 'https://www.axisbank.com/careers', applyUrl: 'https://www.axisbank.com/careers' },
    { name: 'Samsung R&D', category: 'Core', website: 'https://www.samsung.com/global/business/semiconductor/careers', applyUrl: 'https://www.samsung.com/global/business/semiconductor/careers' },
    { name: 'Qualcomm', category: 'Core', website: 'https://www.qualcomm.com/company/careers', applyUrl: 'https://www.qualcomm.com/company/careers' },
    { name: 'Intel', category: 'Core', website: 'https://www.intel.com/content/www/us/en/jobs', applyUrl: 'https://www.intel.com/content/www/us/en/jobs' },
    { name: 'Texas Instruments', category: 'Core', website: 'https://careers.ti.com', applyUrl: 'https://careers.ti.com' },
    { name: 'Nvidia', category: 'Core', website: 'https://www.nvidia.com/en-us/about-nvidia/careers', applyUrl: 'https://www.nvidia.com/en-us/about-nvidia/careers' },
    { name: 'Bosch', category: 'Core', website: 'https://www.bosch.in/careers', applyUrl: 'https://www.bosch.in/careers' },
    { name: 'Honeywell', category: 'Core', website: 'https://careers.honeywell.com', applyUrl: 'https://careers.honeywell.com' },
    { name: 'Oracle', category: 'Product', website: 'https://careers.oracle.com', applyUrl: 'https://careers.oracle.com' },
    { name: 'SAP', category: 'Product', website: 'https://jobs.sap.com', applyUrl: 'https://jobs.sap.com' },
    { name: 'Adobe', category: 'Product', website: 'https://careers.adobe.com', applyUrl: 'https://careers.adobe.com' },
    { name: 'Salesforce', category: 'Product', website: 'https://www.salesforce.com/company/careers', applyUrl: 'https://www.salesforce.com/company/careers' },
    { name: 'ServiceNow', category: 'Product', website: 'https://careers.servicenow.com', applyUrl: 'https://careers.servicenow.com' },
    { name: 'Workday', category: 'Product', website: 'https://www.workday.com/en-us/company/careers', applyUrl: 'https://www.workday.com/en-us/company/careers' },
    { name: 'VMware', category: 'Product', website: 'https://careers.vmware.com', applyUrl: 'https://careers.vmware.com' },
    { name: 'Cisco', category: 'Product', website: 'https://jobs.cisco.com', applyUrl: 'https://jobs.cisco.com' },
    { name: 'PayPal', category: 'Product', website: 'https://jobsearch.paypal-corp.com', applyUrl: 'https://jobsearch.paypal-corp.com' },
    { name: 'Airbnb', category: 'Product', website: 'https://careers.airbnb.com', applyUrl: 'https://careers.airbnb.com' },
    { name: 'Twitter / X', category: 'Product', website: 'https://careers.twitter.com', applyUrl: 'https://careers.twitter.com' },
    { name: 'LinkedIn', category: 'Product', website: 'https://careers.linkedin.com', applyUrl: 'https://careers.linkedin.com' },
    { name: 'Spotify', category: 'Product', website: 'https://www.lifeatspotify.com', applyUrl: 'https://www.lifeatspotify.com' },
    { name: 'Atlassian', category: 'Product', website: 'https://www.atlassian.com/company/careers', applyUrl: 'https://www.atlassian.com/company/careers' },
    { name: 'Slack', category: 'Product', website: 'https://slack.com/careers', applyUrl: 'https://slack.com/careers' },
    { name: 'Dropbox', category: 'Product', website: 'https://www.dropbox.com/jobs', applyUrl: 'https://www.dropbox.com/jobs' },
    { name: 'Twilio', category: 'Product', website: 'https://www.twilio.com/company/jobs', applyUrl: 'https://www.twilio.com/company/jobs' },
    { name: 'Shopify', category: 'Product', website: 'https://www.shopify.com/careers', applyUrl: 'https://www.shopify.com/careers' },
    { name: 'Square', category: 'Startup', website: 'https://careers.squareup.com', applyUrl: 'https://careers.squareup.com' },
    { name: 'Stripe', category: 'Startup', website: 'https://stripe.com/jobs', applyUrl: 'https://stripe.com/jobs' },
    { name: 'Plaid', category: 'Startup', website: 'https://plaid.com/careers', applyUrl: 'https://plaid.com/careers' },
    { name: 'Groww', category: 'Startup', website: 'https://groww.in/careers', applyUrl: 'https://groww.in/careers' },
    { name: 'Zerodha', category: 'Startup', website: 'https://zerodha.com/careers', applyUrl: 'https://zerodha.com/careers' },
    { name: 'Navi', category: 'Startup', website: 'https://www.navi.com/careers', applyUrl: 'https://www.navi.com/careers' },
    { name: 'Meesho', category: 'Startup', website: 'https://meesho.io/careers', applyUrl: 'https://meesho.io/careers' },
    { name: 'Rapido', category: 'Startup', website: 'https://rapido.bike/careers', applyUrl: 'https://rapido.bike/careers' },
    { name: 'Urban Company', category: 'Startup', website: 'https://urbancompany.com/careers', applyUrl: 'https://urbancompany.com/careers' },
    { name: 'Lenskart', category: 'Startup', website: 'https://www.lenskart.com/careers', applyUrl: 'https://www.lenskart.com/careers' },
    { name: 'Delhivery', category: 'Startup', website: 'https://www.delhivery.com/careers', applyUrl: 'https://www.delhivery.com/careers' },
    { name: 'Dunzo', category: 'Startup', website: 'https://www.dunzo.com/careers', applyUrl: 'https://www.dunzo.com/careers' },
    { name: 'Naukri (Info Edge)', category: 'Product', website: 'https://careers.infoedge.in', applyUrl: 'https://careers.infoedge.in' },
    { name: 'MakeMyTrip', category: 'Product', website: 'https://careers.makemytrip.com', applyUrl: 'https://careers.makemytrip.com' },
    { name: 'Cleartrip', category: 'Product', website: 'https://www.cleartrip.com/careers', applyUrl: 'https://www.cleartrip.com/careers' },
    { name: 'Yatra', category: 'Product', website: 'https://careers.yatra.com', applyUrl: 'https://careers.yatra.com' },
    { name: 'Dream11', category: 'Product', website: 'https://careers.dream11.com', applyUrl: 'https://careers.dream11.com' },
    { name: 'MPL (Mobile Premier League)', category: 'Startup', website: 'https://mpl.live/careers', applyUrl: 'https://mpl.live/careers' },
    { name: 'upGrad', category: 'Product', website: 'https://careers.upgrad.com', applyUrl: 'https://careers.upgrad.com' },
    { name: 'Unacademy', category: 'Product', website: 'https://unacademy.com/careers', applyUrl: 'https://unacademy.com/careers' },
    { name: 'Vedantu', category: 'Product', website: 'https://www.vedantu.com/about/careers', applyUrl: 'https://www.vedantu.com/about/careers' },
    { name: 'Doubtnut', category: 'Startup', website: 'https://doubtnut.com/careers', applyUrl: 'https://doubtnut.com/careers' },
    { name: 'Naukri.com', category: 'Product', website: 'https://careers.infoedge.in', applyUrl: 'https://careers.infoedge.in' },
    { name: 'Snapdeal', category: 'Product', website: 'https://www.snapdeal.com/info/careers', applyUrl: 'https://www.snapdeal.com/info/careers' },
    { name: 'Myntra', category: 'Product', website: 'https://careers.myntra.com', applyUrl: 'https://careers.myntra.com' },
    { name: 'Nykaa', category: 'Product', website: 'https://nykaa.com/careers', applyUrl: 'https://nykaa.com/careers' },
    { name: 'Mamaearth', category: 'Startup', website: 'https://mamaearth.in/careers', applyUrl: 'https://mamaearth.in/careers' },
    { name: 'boAt', category: 'Startup', website: 'https://boat-lifestyle.com/careers', applyUrl: 'https://boat-lifestyle.com/careers' },
    { name: 'Realme India', category: 'Core', website: 'https://www.realme.com/in/careers', applyUrl: 'https://www.realme.com/in/careers' },
    { name: 'Xiaomi India', category: 'Core', website: 'https://www.mi.com/in/about/careers', applyUrl: 'https://www.mi.com/in/about/careers' },
    { name: 'OnePlus India', category: 'Core', website: 'https://www.oneplus.in/support/careers', applyUrl: 'https://www.oneplus.in/support/careers' },
    { name: 'Bybit', category: 'Startup', website: 'https://bybit.com/en/careers', applyUrl: 'https://bybit.com/en/careers' },
    { name: 'CoinDCX', category: 'Startup', website: 'https://coindcx.com/careers', applyUrl: 'https://coindcx.com/careers' },
    { name: 'WazirX', category: 'Startup', website: 'https://wazirx.com/careers', applyUrl: 'https://wazirx.com/careers' },
    { name: 'INDmoney', category: 'Startup', website: 'https://www.indmoney.com/careers', applyUrl: 'https://www.indmoney.com/careers' },
    { name: 'Slice', category: 'Startup', website: 'https://sliceit.com/careers', applyUrl: 'https://sliceit.com/careers' },
    { name: 'Jupiter', category: 'Startup', website: 'https://jupiter.money/careers', applyUrl: 'https://jupiter.money/careers' },
    { name: 'Fi Money', category: 'Startup', website: 'https://fi.money/careers', applyUrl: 'https://fi.money/careers' },
    { name: 'NPCI', category: 'Finance', website: 'https://www.npci.org.in/careers', applyUrl: 'https://www.npci.org.in/careers' },
    { name: 'RBI', category: 'Finance', website: 'https://rbi.org.in/careers', applyUrl: 'https://rbi.org.in/careers' },
    { name: 'SEBI', category: 'Finance', website: 'https://sebi.gov.in/careers', applyUrl: 'https://sebi.gov.in/careers' },
    { name: 'ISRO', category: 'Core', website: 'https://www.isro.gov.in/Careers.html', applyUrl: 'https://www.isro.gov.in/Careers.html' },
    { name: 'DRDO', category: 'Core', website: 'https://www.drdo.gov.in/careers', applyUrl: 'https://www.drdo.gov.in/careers' },
    { name: 'BARC', category: 'Core', website: 'https://www.barc.gov.in/careers', applyUrl: 'https://www.barc.gov.in/careers' },
    { name: 'HAL', category: 'Core', website: 'https://hal-india.co.in/careers', applyUrl: 'https://hal-india.co.in/careers' },
    { name: 'BHEL', category: 'Core', website: 'https://www.bhel.com/career', applyUrl: 'https://www.bhel.com/career' },
    { name: 'NTPC', category: 'Core', website: 'https://careers.ntpc.co.in', applyUrl: 'https://careers.ntpc.co.in' },
    { name: 'ONGC', category: 'Core', website: 'https://ongcindia.com/careers', applyUrl: 'https://ongcindia.com/careers' },
    { name: 'Reliance Industries', category: 'Core', website: 'https://careers.ril.com', applyUrl: 'https://careers.ril.com' },
    { name: 'L&T Technology Services', category: 'Service', website: 'https://www.ltts.com/careers', applyUrl: 'https://www.ltts.com/careers' },
    { name: 'Persistent Systems', category: 'Service', website: 'https://www.persistent.com/careers', applyUrl: 'https://www.persistent.com/careers' },
    { name: 'NIIT Technologies', category: 'Service', website: 'https://www.niit.com/en/careers', applyUrl: 'https://www.niit.com/en/careers' },
    { name: 'Mastech', category: 'Service', website: 'https://www.mastech.com/careers', applyUrl: 'https://www.mastech.com/careers' },
    { name: 'iGate', category: 'Service', website: 'https://www.igate.com/careers' },
    { name: 'Syntel', category: 'Service', website: 'https://www.atos.net/en/careers' },
    { name: 'Mindtree', category: 'Service', website: 'https://www.mindtree.com/careers' },
    { name: 'NIIT Ltd', category: 'Service', website: 'https://www.niit.com/en/careers' },
    { name: 'Tata Elxsi', category: 'Core', website: 'https://www.tataelxsi.com/careers' },
    { name: 'Cyient', category: 'Core', website: 'https://www.cyient.com/careers' },
    { name: 'KPIT Technologies', category: 'Core', website: 'https://www.kpit.com/careers' },
    { name: 'Tata Power', category: 'Core', website: 'https://www.tatapower.com/careers' },
    { name: 'Siemens', category: 'Core', website: 'https://jobs.siemens.com' },
    { name: 'ABB', category: 'Core', website: 'https://careers.abb' },
    { name: 'Schneider Electric', category: 'Core', website: 'https://www.se.com/in/en/about-us/careers' },
    { name: 'Rockwell Automation', category: 'Core', website: 'https://www.rockwellautomation.com/careers' },
    { name: 'Emerson', category: 'Core', website: 'https://www.emerson.com/en-us/careers' },
    { name: 'Eaton', category: 'Core', website: 'https://eaton.com/careers' },
    { name: 'GE Digital', category: 'Core', website: 'https://jobs.gecareers.com' },
    { name: 'Flex', category: 'Core', website: 'https://flex.com/resources/job-seekers' },
    { name: 'Jabil', category: 'Core', website: 'https://careers.jabil.com' },
    { name: 'Celestica', category: 'Core', website: 'https://www.celestica.com/careers' },
    { name: 'Flextronics', category: 'Core', website: 'https://flex.com/careers' },
    { name: 'Foxconn', category: 'Core', website: 'https://recruitment.foxconn.com' },
    { name: 'Tata Consultancy Services', category: 'Service', website: 'https://www.tcs.com/careers' },
    { name: 'Larsen & Toubro', category: 'Core', website: 'https://www.lntecc.com/careers' },
    { name: 'Mahindra & Mahindra', category: 'Core', website: 'https://www.mahindra.com/careers' },
    { name: 'Tata Motors', category: 'Core', website: 'https://www.tatamotors.com/careers' },
    { name: 'Maruti Suzuki', category: 'Core', website: 'https://www.marutisuzuki.com/corporate/careers' },
    { name: 'Hero MotoCorp', category: 'Core', website: 'https://corporate.heromotocorp.com/careers' },
    { name: 'Bajaj Auto', category: 'Core', website: 'https://www.bajajauto.com/careers' },
    { name: 'Ashok Leyland', category: 'Core', website: 'https://www.ashokleyland.com/careers' },
    { name: 'DXC Technology', category: 'Service', website: 'https://careers.dxc.com' },
    { name: 'Unisys', category: 'Service', website: 'https://www.unisys.com/careers' },
    { name: 'CSC (DXC)', category: 'Service', website: 'https://careers.dxc.com' },
    { name: 'Atos', category: 'Service', website: 'https://atos.net/en/careers' },
    { name: 'Fujitsu', category: 'Service', website: 'https://www.fujitsu.com/global/about/work' },
    { name: 'NTT Data', category: 'Service', website: 'https://careers.nttdata.com' },
    { name: 'Verizon', category: 'Service', website: 'https://jobs.verizon.com' },
    { name: 'AT&T', category: 'Service', website: 'https://www.att.jobs' },
    { name: 'Ericsson', category: 'Product', website: 'https://www.ericsson.com/en/careers' },
    { name: 'Nokia', category: 'Product', website: 'https://careers.nokia.com' },
    { name: 'Motorola Solutions', category: 'Core', website: 'https://careers.motorolasolutions.com' },
    { name: 'Zebra Technologies', category: 'Core', website: 'https://careers.zebra.com' },
    { name: 'Fortive', category: 'Core', website: 'https://www.fortive.com/careers' },
    { name: 'Microchip Technology', category: 'Core', website: 'https://careers.microchip.com' },
    { name: 'Analog Devices', category: 'Core', website: 'https://careers.analog.com' },
    { name: 'NXP Semiconductors', category: 'Core', website: 'https://www.nxp.com/company/careers' },
    { name: 'STMicroelectronics', category: 'Core', website: 'https://www.st.com/content/st_com/en/about/careers' },
    { name: 'Marvell Technology', category: 'Core', website: 'https://jobs.marvell.com' },
    { name: 'MediaTek', category: 'Core', website: 'https://www.mediatek.com/careers' },
    { name: 'Cadence Design', category: 'Core', website: 'https://cadence.com/en_US/home/careers' },
    { name: 'Synopsys', category: 'Core', website: 'https://synopsys.com/company/synopsys-careers.html' },
    { name: 'Mentor Graphics', category: 'Core', website: 'https://eda.sw.siemens.com/en-US/careers' },
    { name: 'ARM Holdings', category: 'Core', website: 'https://www.arm.com/company/careers' },
    { name: 'VLSI Technology', category: 'Core', website: 'https://vlsitechnology.com/careers' },
    { name: 'Renesas', category: 'Core', website: 'https://www.renesas.com/us/en/careers' },
    { name: 'Infineon', category: 'Core', website: 'https://www.infineon.com/cms/en/careers' },
    { name: 'ON Semiconductor', category: 'Core', website: 'https://www.onsemi.com/careers' },
    { name: 'Broadcom', category: 'Core', website: 'https://careers.broadcom.com' },
    { name: 'Mphasis Digital', category: 'Service', website: 'https://careers.mphasis.com' },
    { name: 'Birlasoft', category: 'Service', website: 'https://www.birlasoft.com/careers' },
    { name: 'Sonata Software', category: 'Service', website: 'https://www.sonata-software.com/careers' },
    { name: 'Centric Software', category: 'Service', website: 'https://centricsoftware.com/company/careers' },
    { name: 'GlobalLogic', category: 'Service', website: 'https://www.globallogic.com/careers' },
    { name: 'EPAM Systems', category: 'Service', website: 'https://www.epam.com/careers' },
    { name: 'Nagarro', category: 'Service', website: 'https://www.nagarro.com/en/careers' },
    { name: 'Publicis Sapient', category: 'Consulting', website: 'https://careers.publicissapient.com' },
    { name: 'Thoughtworks', category: 'Consulting', website: 'https://www.thoughtworks.com/careers' },
    { name: '1-800-Flowers', category: 'Mass Recruiter', website: 'https://jobs.1800flowers.com' },
    { name: 'Sutherland', category: 'Mass Recruiter', website: 'https://careers.sutherland.com' },
    { name: 'Genpact', category: 'Mass Recruiter', website: 'https://www.genpact.com/careers' },
    { name: 'EXL Service', category: 'Mass Recruiter', website: 'https://www.exlservice.com/careers' },
    { name: 'WNS Global', category: 'Mass Recruiter', website: 'https://www.wns.com/careers' },
    { name: 'Firstsource', category: 'Mass Recruiter', website: 'https://www.firstsource.com/careers' },
    { name: 'iEnergizer', category: 'Mass Recruiter', website: 'https://www.ienergizer.com/careers' },
    { name: 'Hinduja Global Solutions', category: 'Mass Recruiter', website: 'https://www.hgsworld.com/careers' },
    { name: 'Convergys', category: 'Mass Recruiter', website: 'https://www.concentrix.com/careers' },
    { name: 'Teleperformance', category: 'Mass Recruiter', website: 'https://jobs.teleperformance.com' },
    { name: 'Concentrix', category: 'Mass Recruiter', website: 'https://www.concentrix.com/careers' },
    { name: 'TTEC', category: 'Mass Recruiter', website: 'https://careers.ttec.com' },
    { name: 'Conduent', category: 'Mass Recruiter', website: 'https://careers.conduent.com' },
    { name: 'Startek', category: 'Mass Recruiter', website: 'https://www.startek.com/careers' },
    { name: 'Aegis Communication', category: 'Mass Recruiter', website: 'https://aegisbpo.com/careers' },
    { name: 'Intelenet Global Services', category: 'Mass Recruiter', website: 'https://www.intelenet.net/careers' },
    { name: 'Relia Group', category: 'Mass Recruiter', website: 'https://relia.com/careers' },
    { name: 'Xceltrait', category: 'Mass Recruiter', website: 'https://www.xceltrait.com/careers' },
    { name: 'Datamatics', category: 'Mass Recruiter', website: 'https://www.datamatics.com/careers' },
    { name: 'Cybage Software', category: 'Mass Recruiter', website: 'https://www.cybage.com/careers' },
    { name: 'Mastech Holdings', category: 'Mass Recruiter', website: 'https://www.mastech.com/careers' },
    { name: 'SunTec Business Solutions', category: 'Mass Recruiter', website: 'https://www.suntecgroup.com/careers' },
    { name: 'Microgenetics', category: 'Mass Recruiter', website: 'https://microgenetics.com' },
    { name: 'Synechron', category: 'Service', website: 'https://www.synechron.com/careers' },
    { name: 'NISG', category: 'Service', website: 'https://nisg.org/careers' },
    { name: 'Sapient Corporation', category: 'Consulting', website: 'https://careers.publicissapient.com' },
    { name: 'UST Global', category: 'Service', website: 'https://www.ust.com/en/life-at-ust' },
    { name: 'ITC Infotech', category: 'Service', website: 'https://www.itcinfotech.com/careers' },
    { name: 'CSS Corp', category: 'Service', website: 'https://www.csscorp.com/careers' },
    { name: 'Tata Communications', category: 'Core', website: 'https://www.tatacommunications.com/career' },
    { name: 'Sterlite Technologies', category: 'Core', website: 'https://www.stl.tech/careers' },
    { name: 'HFCL', category: 'Core', website: 'https://www.hfcl.com/careers' },
    { name: 'Tejas Networks', category: 'Core', website: 'https://tejasnetworks.com/careers' },
    { name: 'Subex', category: 'Product', website: 'https://subex.com/careers' },
    { name: 'Sasken Technologies', category: 'Core', website: 'https://www.sasken.com/careers' },
    { name: 'Xchanging', category: 'Service', website: 'https://careers.dxc.com' },
    { name: 'Patni Computer Systems', category: 'Service', website: 'https://www.igate.com/careers' },
    { name: 'Rolta India', category: 'Service', website: 'https://www.rolta.com/careers' },
    { name: '3i Infotech', category: 'Service', website: 'https://www.3i-infotech.com/careers' },
    { name: 'Zensar Technologies', category: 'Service', website: 'https://www.zensar.com/careers' },
    { name: 'Nucleus Software', category: 'Product', website: 'https://nucleussoftware.com/careers' },
    { name: 'Mastek Group', category: 'Service', website: 'https://mastek.com/careers' },
    { name: 'Quovantis Technologies', category: 'Startup', website: 'https://quovantis.com/careers' },
    { name: 'Clarivate Analytics', category: 'Product', website: 'https://clarivate.com/careers' },
    { name: 'Axt', category: 'Startup', website: 'https://www.axt.com/careers' },
    { name: 'Postman', category: 'Startup', website: 'https://www.postman.com/careers' },
    { name: 'BrowserStack', category: 'Startup', website: 'https://www.browserstack.com/careers' },
    { name: 'Hasura', category: 'Startup', website: 'https://hasura.io/careers' },
    { name: 'Wingify', category: 'Startup', website: 'https://wingify.com/about/#careers' },
    { name: 'Sifters', category: 'Startup', website: 'https://siftery.com/careers' },
    { name: 'Darwinbox', category: 'Startup', website: 'https://darwinbox.com/careers' },
    { name: 'Chargebee', category: 'Startup', website: 'https://www.chargebee.com/careers' },
    { name: 'Mixpanel', category: 'Startup', website: 'https://mixpanel.com/careers' },
    { name: 'CleverTap', category: 'Startup', website: 'https://clevertap.com/about/careers' },
    { name: 'MoEngage', category: 'Startup', website: 'https://www.moengage.com/about/careers' },
    { name: 'WebEngage', category: 'Startup', website: 'https://webengage.com/company/careers' },
    { name: 'Netcore Cloud', category: 'Startup', website: 'https://netcorecloud.com/careers' },
    { name: 'Yellowmessenger', category: 'Startup', website: 'https://yellow.ai/careers' },
    { name: 'Haptik', category: 'Startup', website: 'https://haptik.ai/careers' },
    { name: 'Niki.ai', category: 'Startup', website: 'https://niki.ai/careers' },
    { name: 'Observe.AI', category: 'Startup', website: 'https://www.observe.ai/company/careers' },
    { name: 'Sprinklr', category: 'Startup', website: 'https://sprinklr.com/careers' },
    { name: 'Gupshup', category: 'Startup', website: 'https://www.gupshup.io/careers' },
    { name: 'Agora', category: 'Startup', website: 'https://www.agora.io/en/careers' },
    { name: 'Milkbasket', category: 'Startup', website: 'https://milkbasket.com/careers' },
    { name: 'GreatLearning', category: 'Product', website: 'https://mygreatlearning.com/careers' },
    { name: 'Scaler Academy', category: 'Product', website: 'https://www.scaler.com/about/careers' },
    { name: 'Coding Ninjas', category: 'Product', website: 'https://www.codingninjas.com/about-us' },
    { name: 'Prepbytes', category: 'Startup', website: 'https://prepbytes.com' },
    { name: 'InterviewBit', category: 'Product', website: 'https://www.interviewbit.com/pages/jobs' },
    { name: 'Salesken', category: 'Startup', website: 'https://salesken.ai/careers' },
    { name: 'Zeta', category: 'Startup', website: 'https://www.zeta.in/careers' },
    { name: 'Niyo', category: 'Startup', website: 'https://niyo.in/careers' },
    { name: 'Open Financial', category: 'Startup', website: 'https://open.money/careers' },
    { name: 'Khatabook', category: 'Startup', website: 'https://khatabook.com/careers' },
    { name: 'OkCredit', category: 'Startup', website: 'https://okcredit.in/careers' },
    { name: 'BharatPe', category: 'Startup', website: 'https://bharatpe.com/careers' },
    { name: 'FamPay', category: 'Startup', website: 'https://fampay.in/careers' },
    { name: 'Simpl', category: 'Startup', website: 'https://simpl.com/careers' },
    { name: 'LazyPay', category: 'Startup', website: 'https://lazypay.in/careers' },
    { name: 'KreditBee', category: 'Startup', website: 'https://kreditbee.in/careers' },
    { name: 'MoneyTap', category: 'Startup', website: 'https://www.moneytap.com/careers' },
    { name: 'EarlySalary', category: 'Startup', website: 'https://fibe.in/careers' },
    { name: 'Rupeek', category: 'Startup', website: 'https://www.rupeek.com/careers' },
    { name: 'Lendingkart', category: 'Startup', website: 'https://www.lendingkart.com/careers' },
    { name: 'Capital Float', category: 'Startup', website: 'https://capitalfloat.com/careers' },
    { name: 'Fino Payments Bank', category: 'Finance', website: 'https://www.finobank.com/careers' },
    { name: 'Paytm Money', category: 'Finance', website: 'https://paytmmoney.com/careers' },
    { name: 'Scripbox', category: 'Finance', website: 'https://scripbox.com/careers' },
    { name: 'Smallcase', category: 'Startup', website: 'https://smallcase.com/careers' },
    { name: 'Coin by Zerodha', category: 'Startup', website: 'https://zerodha.com/careers' },
    { name: 'ET Money', category: 'Startup', website: 'https://www.etmoney.com/careers' },
    { name: 'Wealth Management AI', category: 'Startup', website: 'https://wealth.in/careers' },
    { name: 'Artivatic.AI', category: 'Startup', website: 'https://artivatic.ai/careers' },
    { name: 'Innovaccer', category: 'Startup', website: 'https://innovaccer.com/company/careers' },
    { name: 'Practo', category: 'Product', website: 'https://practo.com/careers' },
    { name: 'Lybrate', category: 'Startup', website: 'https://lybrate.com/careers' },
    { name: '1mg', category: 'Product', website: 'https://www.1mg.com/careers' },
    { name: 'PharmEasy', category: 'Product', website: 'https://pharmeasy.in/careers' },
    { name: 'Medlife', category: 'Startup', website: 'https://www.medlife.com/about-us/careers' },
    { name: 'Netmeds', category: 'Startup', website: 'https://www.netmeds.com/careers' },
    { name: 'Apollo Pharmacy', category: 'Core', website: 'https://apollopharmacy.in/careers' },
    { name: 'Narayana Health', category: 'Core', website: 'https://www.narayanahealth.org/careers' },
    { name: 'Aster DM Healthcare', category: 'Core', website: 'https://www.asterhospitals.in/careers' },
    { name: 'Pristyn Care', category: 'Startup', website: 'https://pristyncare.com/careers' },
    { name: 'DocPrime', category: 'Startup', website: 'https://docprime.com/careers' },
];

export const CATEGORIES = ['All', 'FAANG', 'Product', 'Service', 'Startup', 'Consulting', 'Finance', 'Core', 'Mass Recruiter'];
